<div class="title-header-content">
    <div class="icon-1">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('title-header-icon-1')->toHtml(); ?>
    </div>
    <div class="icon-2">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('title-header-icon-2')->toHtml(); ?>
    </div>
    <div class="icon-3">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('title-header-icon-3')->toHtml(); ?>
    </div>
    <div class="icon-4">
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('title-header-icon-4')->toHtml(); ?>
    </div>
</div>